app/controllers/usuario_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from models.database import Usuario, Persona, Rol, db_session
import bcrypt, arrow
from sqlalchemy.exc import IntegrityError
from datetime import datetime

usuario_controller = Blueprint('usuario_controller', __name__)
def create_usuario_blueprint():
    # Crear el objeto Blueprint
    usuario_blueprint = Blueprint('usuario', __name__)

    # Definir las rutas y las funciones controladoras
    @usuario_blueprint.route('/usuarios')
    def listar():
        try:
            rol = db_session.query(Rol).filter(Rol.activo == True).all()
            usuarios = db_session.query(Usuario).filter(Usuario.activo == True).all()
            return render_template('usuario/listar.html', usuarios=usuarios, rol=rol)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)
            
    @usuario_blueprint.route('/usuario/nuevo', methods=['GET', 'POST'])
    def nuevo():
        try:
            error = None
            rol = db_session.query(Rol).filter(Rol.activo == True).all()

            if request.method == 'POST':
                nombre_usuario = request.form['nombre_usuario']
                correo = request.form['correo']
                contrasena = request.form['contrasena']
                confirmar_contrasena = request.form['confirmar_contrasena']
                rol_id = request.form['rol_id']
                rut = request.form['rut']
                nombre = request.form['nombre']
                apellido_paterno = request.form['apellido_paterno']
                apellido_materno = request.form['apellido_materno']
                celular = request.form['celular']

                if contrasena != confirmar_contrasena:
                    error = "Las contraseñas no coinciden"
                else:
                    contrasena_hash = bcrypt.hashpw(contrasena.encode(), bcrypt.gensalt())

                    # Verificar si el RUT ya existe en la base de datos
                    persona_existente = db_session.query(Persona).filter_by(rut=rut).first()

                    if persona_existente:
                        error = 'El RUT ya existe en la base de datos.'
                    else:
                        usuario = Usuario(nombre_usuario=nombre_usuario, correo=correo, contrasena=contrasena_hash, rol_id=rol_id)
                        try:
                            db_session.add(usuario)
                            db_session.commit()

                            # Asignar el ID del usuario creado a persona.usuario_id
                            nueva_persona = Persona(usuario_id=usuario.id, rut=rut, nombre=nombre, apellido_paterno=apellido_paterno,
                                                    apellido_materno=apellido_materno, celular=celular)
                            db_session.add(nueva_persona)
                            db_session.commit()

                            flash('El usuario ha sido creado exitosamente.', 'success')
                            return redirect(url_for('usuario.listar'))
                        except IntegrityError:
                            db_session.rollback()
                            error = "El nombre de usuario o correo electrónico ya están en uso"

            return render_template('usuario/nuevo.html', error=error, rol=rol)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)
                    
    @usuario_blueprint.route('/usuarios/papelera')
    def papelera():
        try:
            rol = db_session.query(Rol).filter(Rol.activo == True).all()
            # Obtenemos todos los usuarios de la base de datos
            usuarios = db_session.query(Usuario).filter(Usuario.activo == False).all()
            return render_template('usuario/papelera.html', usuarios=usuarios)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)
            
    @usuario_blueprint.route('/usuario/restaurar/<int:id>', methods=['GET', 'POST'])
    def restaurar(id):
        try:
            rol = db_session.query(Rol).filter(Rol.activo == True).all()
            usuario = db_session.query(Usuario).filter_by(id=id).one()
            if request.method == 'POST':
                usuario.activo = True
                db_session.commit()
                return redirect(url_for('usuario.listar'))
            else:
                return render_template('usuario/restaurar.html', usuario=usuario)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)
            
    @usuario_blueprint.route('/usuario/editar/<int:id>', methods=['GET', 'POST'])
    def editar(id):
        try:
            rol = db_session.query(Rol).filter(Rol.activo == True).all()
            usuario = db_session.query(Usuario).get(id)
            persona = db_session.query(Persona).filter(Persona.usuario_id == usuario.id).one()

            if usuario is None:
                flash('El usuario no existe', 'error')
                return redirect(url_for('usuario.listar'))

            if request.method == 'POST':
                try:
                    nombre_usuario = request.form['nombre_usuario']
                    correo = request.form['correo']
                    contrasena = request.form['contrasena']
                    confirmar_contrasena = request.form['confirmar_contrasena']
                    rol_id = request.form['rol_id']
                    rut = request.form['rut']
                    nombre = request.form['nombre']
                    apellido_paterno = request.form['apellido_paterno']
                    apellido_materno = request.form['apellido_materno']
                    celular = request.form['celular']

                    # Validar formulario
                    if not nombre_usuario:
                        flash('El nombre de usuario es requerido', 'error')
                    elif not correo:
                        flash('El correo electrónico es requerido', 'error')
                    elif contrasena != confirmar_contrasena:
                        flash('Las contraseñas no coinciden', 'error')
                    else:
                        # Actualizar usuario
                        usuario.nombre_usuario = nombre_usuario
                        usuario.correo = correo
                        usuario.rol_id = rol_id

                        # Si se proporciona una nueva contraseña, se actualiza
                        if contrasena:
                            contrasena_hash = bcrypt.hashpw(contrasena.encode(), bcrypt.gensalt())
                            usuario.contrasena = contrasena_hash

                        usuario.ultima_modificacion = datetime.now()
                        db_session.commit()

                        # Actualizar los datos de la persona asociada al usuario
                        if persona:
                            persona.rut = rut
                            persona.nombre = nombre
                            persona.apellido_paterno = apellido_paterno
                            persona.apellido_materno = apellido_materno
                            persona.celular = celular
                            persona.ultima_modificacion = datetime.now()
                        db_session.commit()

                        flash('Usuario actualizado exitosamente', 'success')
                        return redirect(url_for('usuario.listar'))
                except Exception as e:
                    db_session.rollback()
                    # Manejar el error de alguna manera, como imprimirlo en la consola o mostrar un mensaje al usuario
                    print(f"Error: {e}")
                    # Renderizar un template de error o redirigir a una página de error
                    return render_template('error.html', error_message=str(e))
            return render_template('usuario/editar.html', usuario=usuario, rol=rol, persona=persona)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)
            
    @usuario_blueprint.route('/usuario/eliminar/<int:id>', methods=['GET', 'POST'])
    def eliminar(id):
        try:
            usuario = db_session.query(Usuario).filter_by(id=id).one()
            if request.method == 'POST':
                usuario.activo = False
                db_session.commit()
                return redirect(url_for('usuario.listar'))
            else:
                return render_template('usuario/eliminar.html', usuario=usuario)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)
            
    # Devolver el blueprint
    return usuario_blueprint

app/templates/usuario/editar.html
{% extends "base.html" %}

{% block title %}Editar usuario y persona{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-half">
                <h1 class="title">Editar usuario y persona</h1>
                {% include 'messages.html' %}
                <form method="POST">
                    <!-- Usuario -->
                    <div class="field">
                        <label class="label">Nombre de usuario:</label>
                        <div class="control">
                            <input class="input" type="text" name="nombre_usuario" value="{{ usuario.nombre_usuario }}" minlength="5" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Correo electrónico:</label>
                        <div class="control">
                            <input class="input" type="email" name="correo" value="{{ usuario.correo }}" minlength="5" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Contraseña:</label>
                        <div class="control">
                            <input class="input" type="password" name="contrasena">
                            <p class="help">Dejar en blanco si no desea cambiar la contraseña</p>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Confirmar contraseña:</label>
                        <div class="control">
                            <input class="input" type="password" name="confirmar_contrasena">
                            <p class="help">Dejar en blanco si no desea cambiar la contraseña</p>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Rol:</label>
                        <div class="control">
                            <div class="select">
                                <select name="rol_id">
                                    {% for rol in rol %}
                                    <option value="{{ rol.id }}" {% if rol.id == usuario.rol_id %}selected{% endif %}>{{ rol.nombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Persona -->
                    <div class="field">
                        <label class="label">RUT:</label>
                        <div class="control">
                            <input class="input" type="text" name="rut" value="{{ persona.rut }}" minlength="5" maxlength="12" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Nombre:</label>
                        <div class="control">
                            <input class="input" type="text" name="nombre" value="{{ persona.nombre }}" minlength="2" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Apellido paterno:</label>
                        <div class="control">
                            <input class="input" type="text" name="apellido_paterno" value="{{ persona.apellido_paterno }}" minlength="2" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Apellido materno:</label>
                        <div class="control">
                            <input class="input" type="text" name="apellido_materno" value="{{ persona.apellido_materno }}" minlength="2" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Celular:</label>
                        <div class="control">
                            <input class="input" type="text" name="celular" value="{{ persona.celular }}" maxlength="12">
                        </div>
                    </div>                   
                    <div class="field">
                        <div class="control">
                            <button class="button is-primary" type="submit">Guardar</button>
                            <a class="button is-light" href="{{ url_for('usuario.listar') }}">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/usuario/eliminar.html
{% extends "base.html" %}

{% block title %}Mover usuario a la papelera{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">¿Desea mover el usuario a la papelera?</h1>
        <div class="notification is-warning">
            <p>¿Está seguro de que desea mover el usuario "{{ usuario.nombre_usuario }}" a la papelera?</p>
            <form method="post" action="{{ url_for('usuario.eliminar', id=usuario.id) }}">
                <div class="field">
                    <div class="control">
                        <button class="button is-link" type="submit">Mover</button>
                        <a href="{{ url_for('usuario.listar') }}" class="button is-link is-light">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

app/templates/usuario/listar.html
{% extends "base.html" %}

{% block title %}Usuarios{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <div class="column">
                    <div class="buttons is-pulled-right">
                        <a href="{{ url_for('usuario.papelera') }}" class="button is-link is-light">Ir a papelera</a>
                        <a href="{{ url_for('rol.listar') }}" class="button is-link is-light">Configurar roles</a>
                        <a href="{{ url_for('usuario.nuevo') }}" class="button is-link">Agregar Usuario</a>
                    </div>
                    {% if usuarios %}
                    <h1 class="title">Lista de usuarios</h1>
                    {% include 'messages.html' %}
                    <table class="table is-striped is-hoverable is-fullwidth">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre de usuario</th>
                                <th>Correo</th>
                                <th>Rol</th>
                                <th>Fecha de creación</th>
                                <th>Última modificación</th>
                                <th>Activo</th>
                                <th>Editar/Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for usuario in usuarios %}
                            {% if usuario.activo %}
                            <tr>
                                <td>{{ usuario.id }}</td>
                                <td>{{ usuario.nombre_usuario }}</td>
                                <td>{{ usuario.correo }}</td>
                                <td>{{ usuario.rol.nombre }}</td>
                                <td>{{ usuario.fecha_creacion_cl() if usuario.fecha_creacion else None }}</td>
                                <td>{{ usuario.ultima_modificacion_cl() if usuario.ultima_modificacion != usuario.fecha_creacion else 'Nunca modificado' }}</td>
                                <td>{{ 'Sí' if usuario.activo else 'No' }}</td>
                                <td>
                                    <a href="{{ url_for('usuario.editar', id=usuario.id) }}" class="button is-info is-light">
                                      <span class="icon is-small"><i class="fa fa-pencil-alt" aria-hidden="true"></i></i></span>
                                    </a>
                                    <a href="{{ url_for('usuario.eliminar', id=usuario.id) }}" class="button is-danger is-light">
                                      <span class="icon is-small"><i class="fas fa-trash" aria-hidden="true"></i></span>
                                    </a>
                                </td>
                            </tr>
                        {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <h1 class="title is-1">Lista de usuarios</h1>
                <div class="box">
                <div class="notification is-warning">
                    <h2 class="subtitle is-2">No hay usuarios</h2>
                    <p>No hay usuarios.</p>
                </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/usuario/nuevo.html
{% extends "base.html" %}

{% block title %}Crear usuario y persona{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-half">
                <h1 class="title">Crear usuario y persona</h1>
                {% include 'messages.html' %}
                <form method="POST">
                    <!-- Usuario -->
                    <div class="field">
                        <label class="label">Nombre de usuario:</label>
                        <div class="control">
                            <input class="input" type="text" name="nombre_usuario" minlength="5" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Correo electrónico:</label>
                        <div class="control">
                            <input class="input" type="email" name="correo" minlength="5" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Contraseña:</label>
                        <div class="control">
                            <input class="input" type="password" name="contrasena" minlength="5" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Confirmar contraseña:</label>
                        <div class="control">
                            <input class="input" type="password" name="confirmar_contrasena" minlength="5" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Rol:</label>
                        <div class="control">
                            <div class="select">
                                <select name="rol_id">
                                    {% for rol in rol %}
                                    <option value="{{ rol.id }}">{{ rol.nombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Persona -->
                    <div class="field">
                        <label class="label">RUT:</label>
                        <div class="control">
                            <input class="input" type="text" name="rut" minlength="5" maxlength="12" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Nombre:</label>
                        <div class="control">
                            <input class="input" type="text" name="nombre" minlength="2" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Apellido paterno:</label>
                        <div class="control">
                            <input class="input" type="text" name="apellido_paterno" minlength="2" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Apellido materno:</label>
                        <div class="control">
                            <input class="input" type="text" name="apellido_materno" minlength="2" maxlength="30" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Celular:</label>
                        <div class="control">
                            <input class="input" type="text" name="celular" maxlength="12">
                        </div>
                    </div>                    
                    <div class="field">
                        <div class="control">
                            <button class="button is-primary" type="submit">Crear</button>
                            <a class="button is-light" href="{{ url_for('usuario.listar') }}">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/usuario/papelera.html
{% extends "base.html" %}

{% block title %}Usuarios{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <div class="column">
                    <div class="buttons is-pulled-right">
                        <a href="{{ url_for('usuario.listar') }}" class="button is-link is-light">Volver</a>
                    </div>
                    {% if usuarios %}
                    <h1 class="title">Lista de usuarios en la papelera</h1>
                    {% include 'messages.html' %}
                    <table class="table is-striped is-hoverable is-fullwidth">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre de usuario</th>
                                <th>Correo</th>
                                <th>Rol</th>
                                <th>Fecha de creación</th>
                                <th>Última modificación</th>
                                <th>Activo</th>
                                <th>Editar/Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for usuario in usuarios %}
                            {% if not usuario.activo %}
                            <tr>
                                <td>{{ usuario.id }}</td>
                                <td>{{ usuario.nombre_usuario }}</td>
                                <td>{{ usuario.correo }}</td>
                                <td>{{ usuario.rol.nombre }}</td>
                                <td>{{ usuario.fecha_creacion_cl() if usuario.fecha_creacion else None }}</td>
                                <td>{{ usuario.ultima_modificacion_cl() if usuario.ultima_modificacion != usuario.fecha_creacion else 'Nunca modificado' }}</td>
                                <td>{{ 'Sí' if usuario.activo else 'No' }}</td>
                                <td>
                                    <a href="{{ url_for('usuario.restaurar', id=usuario.id) }}" class="button is-link is-light is-small">
                                      <i class="fa fa-undo" aria-hidden="true"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <h1 class="title is-1">Lista de usuarios en la papelera</h1>
                <div class="box">
                <div class="notification is-warning">
                    <h2 class="subtitle is-2">No hay usuarios</h2>
                    <p>No hay usuarios en la papelera.</p>
                </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/usuario/restaurar.html
{% extends "base.html" %}

{% block title %}Restaurar usuario{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">Restaurar usuario</h1>
        <div class="notification is-warning">
            <p>¿Está seguro de que desea restaurar la usuario "{{ usuario.nombre_usuario }}"?</p>
            <form method="post" action="{{ url_for('usuario.restaurar', id=usuario.id) }}">
                <div class="field">
                    <div class="control">
                        <button class="button is-success" type="submit">Restaurar</button>
                        <a href="{{ url_for('usuario.listar') }}" class="button">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

app/templates/usuario/usuarios.html
{% extends "base.html" %}

{% block title %}Usuarios{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <div class="column">
                    <div class="buttons is-pulled-right">
                        <a href="{{ url_for('usuario_papelera') }}" class="button is-link is-light">Ir a papelera</a>
                        <a href="{{ url_for('usuario_nuevo') }}" class="button is-link">Agregar Usuario</a>
                    </div>
                    <h1 class="title">Usuarios</h1>
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                        <div class="notification is-success">
                            <button class="delete"></button>
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}
                    <table class="table is-striped is-hoverable">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre de usuario</th>
                                <th>Correo</th>
                                <th>Rol</th>
                                <th>Fecha de creación</th>
                                <th>Última modificación</th>
                                <th>Activo</th>
                                <th>Editar/Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for usuario in usuarios %}
                            {% if usuario.activo %}
                            <tr>
                                <td>{{ usuario.id }}</td>
                                <td>{{ usuario.nombre_usuario }}</td>
                                <td>{{ usuario.correo }}</td>
                                <td>{{ usuario.rol.nombre }}</td>
                                <td>{{ arrow.get(usuario.fecha_creacion).to('America/Santiago').format('DD-MM-YYYY HH:mm') if usuario.fecha_creacion else None }}</td>
                                <td>{{ arrow.get(usuario.ultima_modificacion).to('America/Santiago').format('DD-MM-YYYY HH:mm') if usuario.ultima_modificacion != usuario.fecha_creacion else 'Nunca modificado' }}</td>
                                <td>{{ 'Sí' if usuario.activo else 'No' }}</td>
                                <td>
                                    <a href="{{ url_for('usuario_editar', id=usuario.id) }}" class="button is-info is-light">
                                      <span class="icon is-small"><i class="fa fa-pencil-alt" aria-hidden="true"></i></i></span>
                                    </a>
                                    <a href="{{ url_for('usuario_eliminar', id=usuario.id) }}" class="button is-danger is-light">
                                      <span class="icon is-small"><i class="fas fa-trash" aria-hidden="true"></i></span>
                                    </a>
                                  </td>
                            </tr>
                        {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}