app/controllers/ingrediente_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.database import Ingrediente, UnidadMedida, db_session
from datetime import datetime
from sqlalchemy import asc

ingrediente_controller = Blueprint('ingrediente_controller', __name__)
def create_ingrediente_blueprint():
    # Crear el objeto Blueprint
    ingrediente_blueprint = Blueprint('ingrediente', __name__)

    # Definir las rutas y las funciones controladoras
    @ingrediente_blueprint.route('/ingredientes')
    def listar():
        try:
            # Obtenemos todas los ingredientes de la base de datos
            ingredientes = db_session.query(Ingrediente).filter(Ingrediente.activo == True).order_by(asc(Ingrediente.nombre)).all()
            return render_template('ingrediente/listar.html', ingredientes=ingredientes)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)

    @ingrediente_blueprint.route('/ingrediente_papelera')
    def papelera():
        try:
            # Obtenemos todas los ingredientes de la base de datos
            ingredientes = db_session.query(Ingrediente).filter(Ingrediente.activo == False).order_by(asc(Ingrediente.nombre)).all()
            return render_template('ingrediente/papelera.html', ingredientes=ingredientes)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)

    @ingrediente_blueprint.route('/ingrediente_nuevo', methods=['GET', 'POST'])
    def nuevo():
        try:
            # Obtener las categorías para mostrarlas en el formulario
            unidadmedida = db_session.query(UnidadMedida).filter(UnidadMedida.activo == True).all()
            if request.method == 'POST':
                # Obtener los datos del formulario
                nombre = request.form['nombre']
                precio = request.form['precio']
                cantidad = request.form['cantidad']
                unidadmedida_id = request.form['unidadmedida_id']
                alerta_stock = request.form['alerta_stock']
                extra_mediana = request.form['extra_mediana']
                extra_familiar = request.form['extra_familiar']
                # Crear una nueva instancia de Producto con los datos del formulario
                nuevo_ingrediente = Ingrediente(nombre=nombre,
                                        precio=precio, 
                                        cantidad=cantidad, 
                                        unidadmedida_id=unidadmedida_id,
                                        alerta_stock=alerta_stock,
                                        extra_mediana=extra_mediana,
                                        extra_familiar=extra_familiar,
                                        fecha_creacion=datetime.now(),
                                        ultima_modificacion=datetime.now())
                
                # Agregar el producto a la base de datos
                db_session.add(nuevo_ingrediente)
                db_session.commit()
                
                # Redireccionar al listado de productos
                return redirect(url_for('ingrediente.listar'))
            return render_template('ingrediente/nuevo.html', unidadmedida=unidadmedida)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)

    @ingrediente_blueprint.route('/ingrediente_editar/<int:id>', methods=['GET', 'POST'])
    def editar(id):
        try:
            # Obtener el ingrediente a editar de la base de datos
            ingrediente = db_session.query(Ingrediente).filter_by(id=id).one()
            unidadmedida = db_session.query(UnidadMedida).filter(UnidadMedida.activo == True).all()

            if request.method == 'POST':
                # Obtener los datos del formulario
                nombre = request.form['nombre']
                precio = request.form['precio']
                cantidad = request.form['cantidad']
                unidadmedida_id = request.form['unidadmedida_id']
                alerta_stock = request.form['alerta_stock']
                extra_mediana = request.form['extra_mediana']
                extra_familiar = request.form['extra_familiar']

                # Actualizar los datos del ingrediente con los nuevos datos del formulario
                if nombre:
                    ingrediente.nombre = nombre
                if precio:
                    ingrediente.precio = precio
                if cantidad:
                    ingrediente.cantidad = cantidad
                if unidadmedida_id:
                    ingrediente.unidadmedida_id = unidadmedida_id
                if alerta_stock:
                    ingrediente.alerta_stock = alerta_stock
                if extra_mediana:
                    ingrediente.extra_mediana = extra_mediana
                if extra_familiar:
                    ingrediente.extra_familiar = extra_familiar

                # Registrar última modificación
                ingrediente.ultima_modificacion = datetime.now()

                # Guardar los cambios en la base de datos
                db_session.commit()

                # Redireccionar al listado de ingredientes
                return redirect(url_for('ingrediente.listar'))
            return render_template('ingrediente/editar.html', ingrediente=ingrediente, unidadmedida=unidadmedida)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)

    @ingrediente_blueprint.route('/ingrediente_eliminar/<int:id>', methods=['GET', 'POST'])
    def eliminar(id):
        try:
            ingrediente = db_session.query(Ingrediente).filter_by(id=id).one()

            if request.method == 'POST':
                # Eliminar el ingrediente estableciendo el campo "activo" en False
                ingrediente.activo = False
                db_session.commit()

                return redirect(url_for('ingrediente.listar'))
            return render_template('ingrediente/eliminar.html', ingrediente=ingrediente)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)
    @ingrediente_blueprint.route('/ingrediente/restaurar/<int:id>', methods=['GET', 'POST'])
    def restaurar(id):
        try:
            ingrediente = db_session.query(Ingrediente).filter_by(id=id).one()

            if request.method == 'POST':
                ingrediente.activo = True
                db_session.commit()
                return redirect(url_for('ingrediente.listar'))

            return render_template('ingrediente/restaurar.html', ingrediente=ingrediente)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)
    
    @ingrediente_blueprint.route('/ingrediente/ingresar_stock/<int:id>', methods=['GET', 'POST'])
    def ingresar_stock(id):
        try:
            # Obtener el ingrediente a editar de la base de datos
            ingrediente = db_session.query(Ingrediente).filter_by(id=id).one()
            unidadmedida = db_session.query(UnidadMedida).filter(UnidadMedida.activo == True).all()

            if request.method == 'POST':
                # Obtener los datos del formulario
                cantidad = request.form['cantidad']

                # Actualizar los datos del ingrediente con los nuevos datos del formulario
                if cantidad:
                    ingrediente.cantidad = ingrediente.cantidad + int(cantidad)

                # Registrar última modificación
                ingrediente.ultima_modificacion = datetime.now()

                # Guardar los cambios en la base de datos
                db_session.commit()

                return redirect(url_for('reporte.inventario'))

            return render_template('ingrediente/ingresar_stock.html', ingrediente=ingrediente, unidadmedida=unidadmedida)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)

    # Devolver el blueprint
    return ingrediente_blueprint

app/templates/ingrediente/editar.html
{% extends 'base.html' %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Editar ingrediente</h1>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="notification is-success">
            <button class="delete"></button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% endwith %}

    {% if error %}
    <div class="notification is-danger">
        <button class="delete"></button>
        {{ error }}
    </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
      <div class="field">
        <label class="label">Nombre</label>
        <div class="control">
          <input class="input" type="text" name="nombre" value="{{ ingrediente.nombre }}" minlength="3" maxlength="50">
        </div>
      </div>
      <div class="field">
        <label class="label">Precio por ingrediente extra</label>
        <div class="control">
          <p class="control has-icons-left has-icons-right">
          <input class="input" type="number" name="precio" value="{{ ingrediente.precio }}" max="99999">
          <span class="icon is-small is-left">
            <i class="fas fa-dollar-sign"></i>
          </span>
          </p>
        </div>
      </div>
      <div class="field">
        <label class="label">Stock</label>
        <div class="control">
          <div class="input-select-wrapper">
            <input class="input" type="number" name="cantidad" value="{{ ingrediente.cantidad }}" max="2147483646">
            <div class="select-wrapper">
              <div class="select">
                <select name="unidadmedida_id" class="unidadmedida-select">
                  {% for unidadmedida in unidadmedida %}
                  {% if unidadmedida.id == ingrediente.unidadmedida_id %}
                    <option value="{{ unidadmedida.id }}" selected>{{ unidadmedida.nombre }}</option>
                  {% else %}
                    <option value="{{ unidadmedida.id }}">{{ unidadmedida.nombre }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="field">
        <label class="label">Alerta de stock</label><p class="help">Aquí debes asignar un valor para que te notifique alerta de stock del ingrediente en la unidad de medida elegida anteriormente. Por ejemplo: si se eligió gr, se asigna la alerta en gr.</p>
        <div class="control">
          <div class="input-select-wrapper">
            <input class="input" type="number" name="alerta_stock" value="{{ ingrediente.alerta_stock }}" min="0" max="99999" required>
            <div class="select-wrapper">
              <div class="select">
                <select name="unidadmedida_id" class="unidadmedida-select">
                  {% for unidadmedida in unidadmedida %}
                  {% if unidadmedida.id == ingrediente.unidadmedida_id %}
                    <option value="{{ unidadmedida.id }}" selected>{{ unidadmedida.nombre }}</option>
                  {% else %}
                    <option value="{{ unidadmedida.id }}">{{ unidadmedida.nombre }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <h1 class="title">Configuración de porciones extras</h1>
      <div class="field">
        <label class="label">Porción de ingrediente extra para pizza mediana</label><p class="help">Aquí debes asignar la porción del ingrediente en la unidad de medida elegida anteriormente. Por ejemplo: si se eligió gr, se asigna la porción en gr.</p>
        <div class="control">
          <div class="input-select-wrapper">
            <input class="input" type="number" name="extra_mediana" value="{{ ingrediente.extra_mediana }}" min="0" max="99999" required>
            <div class="select-wrapper">
              <div class="select">
                <select name="unidadmedida_id" class="unidadmedida-select">
                  {% for unidadmedida in unidadmedida %}
                  {% if unidadmedida.id == ingrediente.unidadmedida_id %}
                    <option value="{{ unidadmedida.id }}" selected>{{ unidadmedida.nombre }}</option>
                  {% else %}
                    <option value="{{ unidadmedida.id }}">{{ unidadmedida.nombre }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="field">
        <label class="label">Porción de ingrediente extra para pizza familiar</label><p class="help">Aquí debes asignar la porción del ingrediente en la unidad de medida elegida anteriormente. Por ejemplo: si se eligió gr, se asigna la porción en gr.</p>
        <div class="control">
          <div class="input-select-wrapper">
            <input class="input" type="number" name="extra_familiar" value="{{ ingrediente.extra_familiar }}" min="0" max="99999" required>
            <div class="select-wrapper">
              <div class="select">
                <select name="unidadmedida_id" class="unidadmedida-select">
                  {% for unidadmedida in unidadmedida %}
                  {% if unidadmedida.id == ingrediente.unidadmedida_id %}
                    <option value="{{ unidadmedida.id }}" selected>{{ unidadmedida.nombre }}</option>
                  {% else %}
                    <option value="{{ unidadmedida.id }}">{{ unidadmedida.nombre }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="field is-grouped">
        <div class="control">
          <button type="submit" class="button is-link">Guardar</button>
        </div>
        <div class="control">
          <a href="{{ url_for('ingrediente.listar') }}" class="button is-link is-light">Cancelar</a>
        </div>
      </div>
    </form>
  </div>
</section>
<script>
  $(document).ready(function() {
    // Capturar el evento de cambio en los select con la clase "unidadmedida-select"
    $('.unidadmedida-select').change(function() {
      var selectedOption = $(this).val(); // Obtener el valor seleccionado

      // Establecer el mismo valor en los otros select
      $('.unidadmedida-select').not(this).val(selectedOption);
    });
  });
</script>
{% endblock %}

app/templates/ingrediente/eliminar.html
{% extends "base.html" %}

{% block title %}Mover ingrediente a la papelera{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">¿Desea mover el ingrediente a la papelera?</h1>
        <div class="notification is-warning">
            <p>¿Está seguro de que desea mover el ingrediente "{{ ingrediente.nombre }}" a la papelera?</p>
            <form method="post" action="{{ url_for('ingrediente.eliminar', id=ingrediente.id) }}">
                <div class="field">
                    <div class="control">
                        <button class="button is-link" type="submit">Mover</button>
                        <a href="{{ url_for('ingrediente.listar') }}" class="button is-link is-light">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

app/templates/ingrediente/ingresar_stock.html
{% extends 'base.html' %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Ingresar inventario del ingrediente</h1>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="notification is-success">
            <button class="delete"></button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% endwith %}

    {% if error %}
    <div class="notification is-danger">
        <button class="delete"></button>
        {{ error }}
    </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
      <div class="field">
        <label class="label">Nombre</label>
        <div class="control">
          <input class="input" type="text" name="nombre" value="{{ ingrediente.nombre }}" minlength="3" maxlength="50" disabled>
        </div>
      </div>
      <div class="field">
        <label class="label">Cantidad</label>
        <div class="control">
          <div class="input-select-wrapper">
            <input class="input" type="number" name="cantidad" value="1" min="0" max="2147483646">
            <div class="select-wrapper">
              <div class="select">
                <select name="unidadmedida_id" class="unidadmedida-select">
                  {% for unidadmedida in unidadmedida %}
                  {% if unidadmedida.id == ingrediente.unidadmedida_id %}
                    <option value="{{ unidadmedida.id }}" selected disabled>{{ unidadmedida.nombre }}</option>
                  {% else %}
                    <option value="{{ unidadmedida.id }}" disabled>{{ unidadmedida.nombre }}</option>
                  {% endif %}
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="field is-grouped">
        <div class="control">
          <button type="submit" class="button is-link">Guardar</button>
        </div>
        <div class="control">
          <a href="{{ url_for('ingrediente.listar') }}" class="button is-link is-light">Cancelar</a>
        </div>
      </div>
    </form>
  </div>
</section>
<script>
  $(document).ready(function() {
    // Capturar el evento de cambio en los select con la clase "unidadmedida-select"
    $('.unidadmedida-select').change(function() {
      var selectedOption = $(this).val(); // Obtener el valor seleccionado

      // Establecer el mismo valor en los otros select
      $('.unidadmedida-select').not(this).val(selectedOption);
    });
  });
</script>
{% endblock %}

app/templates/ingrediente/listar.html
{% extends "base.html" %}

{% block title %}Ingredientes{% endblock %}

{% block content %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="column">
          <div class="buttons is-pulled-right">
            <a href="{{ url_for('ingrediente.papelera') }}" class="button is-link is-light">Ir a papelera</a>
            <a href="{{ url_for('unidadmedida.listar') }}" class="button is-link is-light">Configurar unidades de medida</a>
            <a href="{{ url_for('ingrediente.nuevo') }}" class="button is-link">Agregar Ingrediente</a>
          </div>
        </div>
        {% if ingredientes %}
        <div class="columns">
          <div class="column">
            <h1 class="title">Lista de Ingredientes</h1>
          </div>
        </div>
        {% include 'messages.html' %}
        <table class="table is-striped is-hoverable is-fullwidth">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Stock</th>
              <th>Alerta de stock</th>
              <th>Ingrediente extra</th>
              <th>Porción extra para mediana</th>
              <th>Porción extra para familiar</th>
              <th>Fecha creación</th>
              <th>Fecha modificación</th>
              <th>Editar/Eliminar</th>
            </tr>
          </thead>
          <tbody>
            {% for ingrediente in ingredientes %}
                <tr>
                  <td>{{ ingrediente.nombre }}</td>
                  <td>{{ ingrediente.cantidad }} {{ ingrediente.unidadmedida.nombre }}</td>
                  <td>{{ ingrediente.alerta_stock }} {{ ingrediente.unidadmedida.nombre }}</td>
                  <td>
                  {% if ingrediente.precio >= 1%}
                    ${{ ingrediente.precio }}
                  {% else %}
                    No es añadible
                  {% endif %}
                  </td>
                  <td>{{ ingrediente.extra_mediana }} {{ ingrediente.unidadmedida.nombre }}</td>
                  <td>{{ ingrediente.extra_familiar }} {{ ingrediente.unidadmedida.nombre }}</td>
                  <td>{{ ingrediente.fecha_creacion_cl() if ingrediente.fecha_creacion else None }}</td>
                  <td>{{ ingrediente.ultima_modificacion_cl() if ingrediente.ultima_modificacion != ingrediente.fecha_creacion else 'Nunca modificado' }}</td>
                  <td>
                    <a href="{{ url_for('ingrediente.editar', id=ingrediente.id) }}" class="button is-warning is-small">
                      <span class="icon is-small"><i class="fa fa-pencil-alt" aria-hidden="true"></i></i></span>
                    </a>
                    <a href="{{ url_for('ingrediente.eliminar', id=ingrediente.id) }}" class="button is-danger is-small">
                      <span class="icon is-small"><i class="fas fa-trash" aria-hidden="true"></i></span>
                    </a>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <h1 class="title is-1">Lista de Ingredientes</h1>
					<div class="box">
						<div class="notification is-warning">
							<h1 class="subtitle is-2">No hay Ingredientes</h2>
							<p>No se han agregado Ingredientes a la base de datos, puedes agregar uno dando click en el boton <b>"Agregar Ingrediente"</b>.</p>
						</div>
					</div>
        {% endif %}
      </div>
    </div>
  </div>
</section>

{% endblock %}

app/templates/ingrediente/nuevo.html
{% extends 'base.html' %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Agregar ingrediente</h1>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="notification is-success">
            <button class="delete"></button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% endwith %}
    <form method="POST" action="{{ url_for('ingrediente.nuevo') }}" enctype="multipart/form-data">
      <div class="field">
        <label class="label">Nombre</label>
        <div class="control">
          <input class="input" type="text" name="nombre" minlength="3" maxlength="50" required>
        </div>
      </div>
      <div class="field">
        <label class="label">Precio</label>
        <div class="control">
          <p class="control has-icons-left has-icons-right">
            <input class="input" type="text" name="precio" value="1000" max="99999" required>
            <span class="icon is-small is-left">
              <i class="fas fa-dollar-sign"></i>
            </span>
          </p>
        </div>
      </div>
      <div class="field">
        <label class="label">Stock</label><p class="help">Si no encuentras la unidad de medida que buscas, ¡puedes crearla <a href="/unidadmedidas">aqui</a>!</p>
        <div class="control">
          <div class="input-select-wrapper">
            <input class="input" type="number" name="cantidad" max="2147483646">
            <div class="select-wrapper">
              <div class="select">
                <select name="unidadmedida_id" class="unidadmedida-select">
                  {% for unidadmedida in unidadmedida %}
                  <option value="{{ unidadmedida.id }}">{{ unidadmedida.nombre }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="field">
        <label class="label">Alerta de stock</label><p class="help">Aquí debes asignar un valor para que te notifique alerta de stock del ingrediente en la unidad de medida elegida anteriormente. Por ejemplo: si se eligió gr, se asigna la alerta en gr.</p>
        <div class="control">
          <div class="input-select-wrapper">
            <input class="input" type="number" name="alerta_stock" value="1" min="0" max="99999" required>
            <div class="select-wrapper">
              <div class="select">
                <select name="unidadmedida_id" class="unidadmedida-select">
                  {% for unidadmedida in unidadmedida %}
                  <option value="{{ unidadmedida.id }}">{{ unidadmedida.nombre }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <h1 class="title">Configuración de porciones extras</h1>
      <div class="field">
        <label class="label">Porción de ingrediente extra para pizza mediana</label><p class="help">Aquí debes asignar la porción del ingrediente en la unidad de medida elegida anteriormente. Por ejemplo: si se eligió gr, se asigna la porción en gr.</p>
        <div class="control">
          <div class="input-select-wrapper">
            <input class="input" type="number" name="extra_mediana" value="1" min="0" max="99999" required>
            <div class="select-wrapper">
              <div class="select">
                <select name="unidadmedida_id" class="unidadmedida-select">
                  {% for unidadmedida in unidadmedida %}
                  <option value="{{ unidadmedida.id }}">{{ unidadmedida.nombre }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="field">
        <label class="label">Porción de ingrediente extra para pizza familiar</label><p class="help">Aquí debes asignar la porción del ingrediente en la unidad de medida elegida anteriormente. Por ejemplo: si se eligió gr, se asigna la porción en gr.</p>
        <div class="control">
          <div class="input-select-wrapper">
            <input class="input" type="number" name="extra_familiar" value="1" min="0" max="99999" required>
            <div class="select-wrapper">
              <div class="select">
                <select name="unidadmedida_id" class="unidadmedida-select">
                  {% for unidadmedida in unidadmedida %}
                  <option value="{{ unidadmedida.id }}">{{ unidadmedida.nombre }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="field is-grouped">
        <div class="control">
          <button type="submit" class="button is-link">Guardar</button>
        </div>
        <div class="control">
          <a href="{{ url_for('ingrediente.listar') }}" class="button is-link is-light">Cancelar</a>
        </div>
      </div>
    </form>
  </div>
</section>
<script>
  $(document).ready(function() {
    // Capturar el evento de cambio en los select con la clase "unidadmedida-select"
    $('.unidadmedida-select').change(function() {
      var selectedOption = $(this).val(); // Obtener el valor seleccionado

      // Establecer el mismo valor en los otros select
      $('.unidadmedida-select').not(this).val(selectedOption);
    });
  });
</script>
{% endblock %}

app/templates/ingrediente/papelera.html
{% extends "base.html" %}

{% block title %}Ingredientes{% endblock %}

{% block content %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="column">
          <div class="buttons is-pulled-right">
            <a href="{{ url_for('ingrediente.listar') }}" class="button is-link is-light">Volver</a>
          </div>
        </div>
        {% if ingredientes %}
        <div class="columns">
          <div class="column">
            <h1 class="title">Lista de ingredientes en la papelera</h1>
          </div>
        </div>
        <table class="table is-striped is-hoverable">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Cantidad</th>
              <th>Restaurar</th>
            </tr>
          </thead>
          <tbody>
            {% for ingrediente in ingredientes %}
            {% if not ingrediente.activo %}
            <tr>
              <td>{{ ingrediente.nombre }}</td>
              <td>{{ ingrediente.cantidad }} {{ ingrediente.unidadmedida.nombre }}</td>
              <td>
                <a href="{{ url_for('ingrediente.restaurar', id=ingrediente.id) }}" class="button is-link is-light is-small">
                  <i class="fa fa-undo" aria-hidden="true"></i>
                </a>
              </td>
            </tr>
            {% endif %}
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <h1 class="title is-1">Lista de ingredientes en la papelera</h1>
        <div class="box">
          <div class="notification is-warning">
            <h2 class="subtitle is-2">No hay ingredientes</h2>
            <p>No hay ingredientes en la papelera.</p>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/ingrediente/restaurar.html
{% extends "base.html" %}

{% block title %}Restaurar ingrediente{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">Restaurar ingrediente</h1>
        <div class="notification is-warning">
            <p>¿Está seguro de que desea restaurar la ingrediente "{{ ingrediente.nombre }}"?</p>
            <form method="post" action="{{ url_for('ingrediente.restaurar', id=ingrediente.id) }}">
                <div class="field">
                    <div class="control">
                        <button class="button is-success" type="submit">Restaurar</button>
                        <a href="{{ url_for('ingrediente.listar') }}" class="button">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}