app/controllers/categoria_controller.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.database import Categoria, db_session
from datetime import datetime
from sqlalchemy import asc

categoria_controller = Blueprint('categoria_controller', __name__)
def create_categoria_blueprint():
    # Crear el objeto Blueprint
    categoria_blueprint = Blueprint('categoria', __name__)

    # Definir las rutas y las funciones controladoras
    @categoria_blueprint.route('/categorias')
    def listar():
        try:
            # Obtenemos todas las categorías de la base de datos
            categorias = db_session.query(Categoria).filter(Categoria.activo == True).order_by(asc(Categoria.nombre)).all()
            return render_template('categoria/listar.html', categorias=categorias)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)

    @categoria_blueprint.route('/categoria/nueva', methods=['GET', 'POST'])
    def nueva():
        try:
            if request.method == 'POST':
                # Obtener los datos del formulario
                nombre = request.form['nombre']

                # Crear una nueva categoría
                nueva_categoria = Categoria(nombre=nombre)

                # Guardar la nueva categoría en la base de datos
                db_session.add(nueva_categoria)
                db_session.commit()

                return redirect(url_for('categoria.listar'))
            return render_template('categoria/nueva.html')
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)

    @categoria_blueprint.route('/categoria/editar/<int:id>', methods=['GET', 'POST'])
    def editar(id):
        try:
            categoria = db_session.query(Categoria).filter_by(id=id).one()
            if request.method == 'POST':
                nombre = request.form['nombre']
                categoria.ultima_modificacion = datetime.now()
                categoria.nombre = nombre
                db_session.commit()
                return redirect(url_for('categoria.listar'))
            else:
                return render_template('categoria/editar.html', categoria=categoria)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)

    @categoria_blueprint.route('/categoria/eliminar/<int:id>', methods=['GET', 'POST'])
    def eliminar(id):
        try:
            categoria = db_session.query(Categoria).filter_by(id=id).one()
            if request.method == 'POST':
                categoria.activo = False
                db_session.commit()
                return redirect(url_for('categoria.listar'))
            else:
                return render_template('categoria/eliminar.html', categoria=categoria)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)

    @categoria_blueprint.route('/categorias/papelera')
    def papelera():
        try:
            # Obtenemos todas los categorias de la base de datos
            categorias = db_session.query(Categoria).filter(Categoria.activo == False).order_by(asc(Categoria.nombre)).all()
            return render_template('categoria/papelera.html', categorias=categorias)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)

    @categoria_blueprint.route('/categoria/restaurar/<int:id>', methods=['GET', 'POST'])
    def restaurar(id):
        try:
            categoria = db_session.query(Categoria).filter_by(id=id).one()
            if request.method == 'POST':
                categoria.activo = True
                db_session.commit()
                return redirect(url_for('categoria.listar'))
            else:
                return render_template('categoria/restaurar.html', categoria=categoria)
        except:
            print("ERROR DESCONOCIDO: informe con el desarrollador sobre este problema.")
            db_session.rollback()
            return redirect(request.path)
    
    # Devolver el blueprint
    return categoria_blueprint

app/templates/categoria/categorias.html
{% extends "base.html" %}

{% block title %}Categorías{% endblock %}

{% block content %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="column">
          <div class="buttons is-pulled-right">
            <a href="{{ url_for('categoria_papelera') }}" class="button is-link is-light">Ir a papelera</a>
            <a href="{{ url_for('categoria_nueva') }}" class="button is-link">Agregar Categoría</a>
          </div>
        </div>
        {% if hay_activas %}
        <div class="columns">
          <div class="column">
            <h1 class="title">Lista de Categorías</h1>
          </div>
        </div>
        <table class="table is-striped is-hoverable">
          <thead>
            <tr>
              <th>Nombre</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for categoria in categorias %}
              {% if categoria.activo %}
                <tr>
                  <td>{{ categoria.nombre }}</td>
                  <td>
                    <a href="{{ url_for('categoria_editar', id=categoria.id) }}" class="button is-warning is-small">
                      <span class="icon is-small"><i class="fa fa-pencil-alt" aria-hidden="true"></i></i></span>
                    </a>
                    <a href="{{ url_for('categoria_eliminar', id=categoria.id) }}" class="button is-danger is-small">
                      <span class="icon is-small"><i class="fas fa-trash" aria-hidden="true"></i></span>
                    </a>
                  </td>
                </tr>
              {% endif %}
            {% endfor %}
          </tbody>
        </table>
        {% endif %}
        <!-- End "if hay_activas" -->
        {% if not hay_activas %}
        <h1 class="title is-1">Lista de Categorías</h1>
					<div class="box">
						<div class="notification is-warning">
							<h1 class="subtitle is-2">No hay Categorías</h2>
							<p>No se han agregado Categorías a la base de datos, puedes agregar uno dando click en el boton <b>"Agregar Producto"</b>.</p>
						</div>
					</div>
        {% endif %}
      </div>
    </div>
  </div>
</section>

{% endblock %}

app/templates/categoria/editar.html
{% extends 'base.html' %}
{% block title %}Categoría{% endblock %}
{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Editar Categoría</h1>
    <form method="post">
      <div class="field">
        <label class="label">Nombre</label>
        <div class="control">
          <input class="input" type="text" name="nombre" value="{{ categoria.nombre }}" minlength="3" maxlength="50" required>
        </div>
      </div>
      <div class="field is-grouped">
        <div class="control">
          <button type="submit" class="button is-link">Guardar</button>
        </div>
        <div class="control">
          <a href="{{ url_for('categoria.listar') }}" class="button is-link is-light">Cancelar</a>
        </div>
      </div>
    </form>
  </div>
</section>
{% endblock %}

app/templates/categoria/eliminar.html
{% extends "base.html" %}
{% block title %}Eliminar Categoría{% endblock %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">Eliminar Categoría</h1>
        <div class="notification is-warning">
            <p>¿Está seguro de que desea eliminar la categoría "{{ categoria.nombre }}"?</p>
            <form method="post" action="{{ url_for('categoria.eliminar', id=categoria.id) }}">
                <div class="field">
                    <div class="control">
                        <button class="button is-danger" type="submit">Eliminar</button>
                        <a href="{{ url_for('categoria.listar') }}" class="button">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

app/templates/categoria/listar.html
{% extends "base.html" %}
{% block title %}Categorías{% endblock %}
{% block content %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="column">
          <div class="buttons is-pulled-right">
            <a href="{{ url_for('categoria.papelera') }}" class="button is-link is-light">Ir a papelera</a>
            <a href="{{ url_for('categoria.nueva') }}" class="button is-link">Agregar Categoría</a>
          </div>
        </div>
        {% if categorias %}
        <div class="columns">
          <div class="column">
            <h1 class="title">Lista de Categorías</h1>
          </div>
        </div>
        {% include 'messages.html' %}
        <table class="table is-striped is-hoverable">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Fecha creación</th>
              <th>Fecha modificación</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for categoria in categorias %}
                <tr>
                  <td>{{ categoria.nombre }}</td>
                  <td>{{ categoria.fecha_creacion_cl() if categoria.fecha_creacion else None }}</td>
                  <td>{{ categoria.ultima_modificacion_cl() if categoria.ultima_modificacion != categoria.fecha_creacion else 'Nunca modificado' }}</td>
                  <td>
                    <a href="{{ url_for('categoria.editar', id=categoria.id) }}" class="button is-warning is-small">
                      <span class="icon is-small"><i class="fa fa-pencil-alt" aria-hidden="true"></i></i></span>
                    </a>
                    <a href="{{ url_for('categoria.eliminar', id=categoria.id) }}" class="button is-danger is-small">
                      <span class="icon is-small"><i class="fas fa-trash" aria-hidden="true"></i></span>
                    </a>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <h1 class="title is-1">Lista de Categorías</h1>
					<div class="box">
						<div class="notification is-warning">
							<h1 class="subtitle is-2">No hay Categorías</h2>
							<p>No se han agregado Categorías a la base de datos, puedes agregar uno dando click en el boton <b>"Agregar Categoría"</b>.</p>
						</div>
					</div>
        {% endif %}
      </div>
    </div>
  </div>
</section>

{% endblock %}

app/templates/categoria/nueva.html
{% extends "base.html" %}
{% block title %}Nueva categoría{% endblock %}
{% block content %}
<section class="section">
  <div class="container">
      <div class="columns">
        <div class="column is-10 is-offset-1">
          <h1 class="title is-1">Nueva Categoría</h1>
          <br>
          <form method="post" enctype="multipart/form-data" id="categoria_nueva" action="{{ url_for('categoria.nueva') }}" role="form">
            <div class="field">
              <label class="label">Nombre*</label>
              <div class="control">
                <input type="text" name="nombre" class="input" id="nombre" placeholder="Nombre de la categoria" minlength="3" maxlength="50" required>
              </div>
            </div>
            <div class="field">
              <div class="control">
                <button type="submit" class="button is-link">Agregar Categoría</button>
                <a href="{{ url_for('categoria.listar') }}" class="button is-link is-light">Cancelar</a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

app/templates/categoria/papelera.html
{% extends "base.html" %}
{% block title %}Papelera{% endblock %}
{% block content %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="column">
          <div class="buttons is-pulled-right">
            <a href="{{ url_for('categoria.listar') }}" class="button is-link is-light">Volver</a>
          </div>
        </div>
        {% if categorias %}
        <div class="columns">
          <div class="column">
            <h1 class="title">Lista de categorias en la papelera</h1>
          </div>
        </div>
        <table class="table is-bordered is-hoverable">
          <thead>
            <tr>
              <th>Nombre</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for categoria in categorias %}
                <tr>
                  <td>{{ categoria.nombre }}</td>
                  <td>
                    <a href="{{ url_for('categoria.restaurar', id=categoria.id) }}" class="button is-link is-light is-small">
                      <i class="fa fa-undo" aria-hidden="true"></i>
                    </a>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <h1 class="title is-1">Lista de categorias en la papelera</h1>
					<div class="box">
						<div class="notification is-warning">
							<h1 class="subtitle is-2">No hay Categorías</h2>
							<p>No hay categorias en la papelera.</p>
						</div>
					</div>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/categoria/restaurar.html
{% extends "base.html" %}
{% block title %}Restaurar categoria{% endblock %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">Restaurar categoria</h1>
        <div class="notification is-warning">
            <p>¿Está seguro de que desea restaurar la categoria "{{ categoria.nombre }}"?</p>
            <form method="post" action="{{ url_for('categoria.restaurar', id=categoria.id) }}">
                <div class="field">
                    <div class="control">
                        <button class="button is-success" type="submit">Restaurar</button>
                        <a href="{{ url_for('categoria.listar') }}" class="button">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}